USE [BUDT703_Project_0506_06];

BEGIN TRANSACTION;

DROP TABLE IF EXISTS [Master_Lee's.Order];
DROP TABLE IF EXISTS [Master_Lee's.MenuCuisine];
DROP TABLE IF EXISTS [Master_Lee's.Menu];
DROP TABLE IF EXISTS [Master_Lee's.Employ];
DROP TABLE IF EXISTS [Master_Lee's.DeliveryPlatform];
DROP TABLE IF EXISTS [Master_Lee's.Review];
DROP TABLE IF EXISTS [Master_Lee's.Customer];
DROP TABLE IF EXISTS [Master_Lee's.Restaurant];

CREATE TABLE [Master_Lee's.Restaurant] (
	rstId CHAR(5) NOT NULL,
	rstName VARCHAR(20),
	rstCapacity DECIMAL(3,0),
	rstDistance DECIMAL(5,2),
	rstStreet VARCHAR(30),
	rstLatitude DECIMAL(8,2),
	rstLongtitude DECIMAL(8,2),
	rstCity VARCHAR(20),
	rstZip CHAR(5),
	rstParking BIT,
	rstWiFi BIT,
    CONSTRAINT pk_Restaurant_rstId PRIMARY KEY (rstId)
    );

CREATE TABLE [Master_Lee's.Customer] (
    cstId CHAR(5) NOT NULL,
    cstName VARCHAR(20),
    cstGender BIT,
    cstAge VARCHAR(5),
    CONSTRAINT pk_Customers_cstId PRIMARY KEY (cstId)
    );

CREATE TABLE [Master_Lee's.Review] (
    rvwRating DECIMAL(1,0) NOT NULL,
    rvwStatement VARCHAR(1000),
    rvwDate DATE,
    rstId CHAR(5) NOT NULL,
    cstId CHAR(5) NOT NULL,
    CONSTRAINT pk_Review_rstId_cstId PRIMARY KEY (rstId, cstId),
    CONSTRAINT fk_Review_rstId FOREIGN KEY (rstId)
		REFERENCES [Master_Lee's.Restaurant] (rstId)
		ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT fk_Review_cstId FOREIGN KEY (cstId)
		REFERENCES [Master_Lee's.Customer] (cstId)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    )

CREATE TABLE [Master_Lee's.DeliveryPlatform] (
    pltName VARCHAR(20) NOT NULL,
    pltWebsite XML,
    CONSTRAINT pk_DeliveryPlatform_pltName PRIMARY KEY (pltName),
    );

CREATE TABLE [Master_Lee's.Employ] (
    rstId CHAR(5) NOT NULL,
    pltName VARCHAR(20) NOT NULL,
    CONSTRAINT pk_Employ_rstId_pltName PRIMARY KEY (rstId, pltName),
    CONSTRAINT fk_Employ_rstId FOREIGN KEY (rstId)
		REFERENCES [Master_Lee's.Restaurant] (rstId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_Employ_pltName FOREIGN KEY (pltName)
		REFERENCES [Master_Lee's.DeliveryPlatform] (pltName)
		ON DELETE CASCADE ON UPDATE CASCADE,
    );

CREATE TABLE [Master_Lee's.Menu] (
    rstId CHAR(5) NOT NULL,
    mnuId CHAR(5) NOT NULL,
    mnuPriceRange DECIMAL(4,2),
    mnuDrink BIT,
    CONSTRAINT pk_Menu_rstId_mnuId PRIMARY KEY (rstId, mnuId),
    CONSTRAINT fk_Menu_rstId FOREIGN KEY (rstId)
		REFERENCES [Master_Lee's.Restaurant] (rstId)
		ON DELETE CASCADE ON UPDATE CASCADE,
    );

CREATE TABLE [Master_Lee's.MenuCuisine] (
    rstId CHAR(5) NOT NULL,
    mnuId CHAR(5) NOT NULL,
    mnuCuisine VARCHAR(30) NOT NULL,
    CONSTRAINT pk_MenuCuisine_rstId_mnuId_mnuCuisine PRIMARY KEY (rstId, mnuId, mnuCuisine),
    CONSTRAINT fk_MenuCuisine_rstId_mnuId FOREIGN KEY (rstId, mnuId)
		REFERENCES [Master_Lee's.Menu] (rstId, mnuId)
		ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE [Master_Lee's.Order] (
	rstId CHAR(5) NOT NULL,
    cstId CHAR(5) NOT NULL,
	CONSTRAINT pk_Order_rstId_cstId PRIMARY KEY (rstId, cstId),
	CONSTRAINT fk_Order_rstId FOREIGN KEY (rstId)
		REFERENCES [Master_Lee's.Restaurant] (rstId)
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT fk_Order_cstId FOREIGN KEY (cstId)
		REFERENCES [Master_Lee's.Customer] (cstId)
		ON DELETE NO ACTION ON UPDATE NO ACTION
	);


SET ANSI_WARNINGS OFF;

INSERT INTO [Master_Lee's.Restaurant] VALUES
('R1001', 'Potomac Pizza', 100, 0.1, '7777 Baltimore Ave', 38.9870823, -76.9349577, 'College Park', 20740, 1, 1),
('R1002', 'Ledo Pizza', 60, 0.2, '4509 Knox Rd', 38.9805915, -76.9371251, 'College Park', 20740, 1, 1),
('R1003', 'Blaze Fast-Fire''d Pizza', 30, 0.09, '7419 Baltimore Ave', 38.981744, -76.937539, 'College Park', 20740, 1, 1),
('R1004', 'Mamma Lucia''s', 100, 2, '4634 Cherry Hill Road', 39.926813, -75.0246312, 'College Park', 20740, 1, 0),
('R1005', 'Slices Pizza Co.', 20, 0.8, '7313 Baltimore Ave Ste C', 38.979919, -76.937608, 'College Park', 20740, 1, 0),
('R1006', 'Pizza Roma', 25, 2.2, '9805 Rhode Island Avenue', 39.0142057, -76.9196899, 'College Park', 20740, 1, 0),
('R1007', 'Pizza Kindom', 20, 0.09, '4439 Lehigh Rd', 38.9817004, -76.9381282, 'College Park', 20740, 1, 1),
('R1008', 'College Park Grill', 70, 0.9, '8321 Baltimore Ave suite b', 38.9929501, -76.9319414, 'College Park', 20740, 1, 0),
('R1009', 'Dumm''s Pizza and Subs', 25, 1.9, '4704 Riverdale Rd', 38.9620304, -76.9349125999999, 'Riverdale', 20737, 0, 0),
('R1010', 'Three Brothers Italian Restaurant', 50, 2.1, '6160 Greenbelt Rd', 38.9995179999999, -76.9072322, 'Greenbelt', 20770, 0, 0),
('R1011', 'Pizza Oven', 25, 3.1, '6029 66th Ave', 38.9607912, -76.903013, 'Riverdale', 20737, 0, 0),
('R1012', 'Pizzeria Paradiso', 50, 2.8, '4800 Rhode Island Ave', 38.9485296, -76.9438259, 'Hyattsville', 20781, 1, 0),
('R1013', 'Roscoe''s', 50, 4, '7040 Carroll Ave', 38.975252, -77.0112173, 'Takoma Park', 20912, 0, 0),
('R1014', '&pizza - H Street', 30, 7.1, '1118 H St NE', 38.9004061, -76.9907788, 'Washington, DC', 20002, 0, 1),
('R1015', 'Manny & Olga''s Pizza', 0, 7.6, '1841 14th St NW', 38.9152682, -77.0316747999999, 'Washington, DC', 20009, 0, 0),
('R1016', 'Pi Pizzeria', 100, 8.7, '910 F St NW', 38.8971483, -77.0247023, 'Washington, DC', 20004, 0, 1),
('R1017', 'Spice 6', 50, 2.7, '5501 Baltimore Ave Ste 107', 38.9556625, -76.9399096, 'Hyattsville', 20781, 1, 1),
('R1018', 'Menomale', 50, 4.8, '2711 12th St NE', 38.92498, -76.98992, 'Washington, DC', 20018, 0, 0),
('R1019', 'Generous Joe''s Deli', 20, 4.08, '107 Centerway Ste A', 39.00117, -76.87657, 'Greenbelt', 20770, 1, 0),
('R1020', 'Vapiano M Street', 60, 7.48, '1800 M. St NW', 38.90552, -77.04188, 'Washington, DC', 20003, 1, 1);

INSERT INTO [Master_Lee's.Customer] VALUES
('C0001', 'Colette K', 0, '50-64'),
('C0002', 'Jasmine', 0, '18-24'),
('C0003', 'Nishant S', 1, '18-24'),
('C0004', 'Mary M', 0, '50-64'),
('C0005', 'JerseyGrown91', 0, '25-34'),
('C0006', 'J David H', 1, '35-49'),
('C0007', 'Patomoment', 1, '25-34'),
('C0008', 'SHC5015', 1, '50-64'),
('C0009', 'ShanteA''', 0, '35-49'),
('C0010', 'Natasha M', 0, '35-49'),
('C0011', 'Ant1007', 1, '35-49'),
('C0012', 'bid421', 0, '35-49'),
('C0013', 'wernolabound', 1, '50-64'),
('C0014', 'AlanLosAngeles_CA', 1, '65+'),
('C0015', 'nedtraveler', 1, '65+'),
('C0016', 'Natalie B', 0, '25-34'),
('C0017', 'HerrP', 1, '50-64'),
('C0018', 'ArchieTSB32', 1, '50-64'),
('C0019', 'Omar S', 1, '35-49'),
('C0020', 'RussL', 1, '50-64'),
('C0021', '2013TravelinFool', 0, '50-64'),
('C0022', 'bassaidai88', 0, '50-64'),
('C0023', 'HBH2336', 0, '35-49'),
('C0024', 'BDD99', 0, '50-64'),
('C0025', 'Haley K', 0, '18-24'),
('C0026', 'Hickory Ridge', 1, '50-64'),
('C0027', 'Kalvay H', 1, '35-49'),
('C0028', 'C_Razzano', 0, '35-49'),
('C0029', 'Lynda Heidi P', 0, '65+'),
('C0030', 'jaseaton', 1, '65+'),
('C0031', 'Chris C', 1, '35-49'),
('C0032', 'Paoball', 0, '50-64'),
('C0033', 'DCGustavson', 1, '25-34'),
('C0034', 'Laura C', 0, '50-64'),
('C0035', 'Mowna', 0, '25-34'),
('C0036', 'Dean B', 1, '50-64'),
('C0037', 'Wheatleigh D', 1, '35-49'),
('C0038', 'Marco C', 1, '50-64'),
('C0039', 'Regina S', 0, '50-64'),
('C0040', 'TIm B', 1, '35-49'),
('C0041', 'Jill S', 0, '35-49'),
('C0042', '799howardsw', 1, '25-34'),
('C0043', 'D4379', 1, '50-64'),
('C0044', 'lazypizza', 1, '35-49'),
('C0045', 'SirShanman', 1, '35-49'),
('C0047', 'emped0cles', 1, '35-49'),
('C0048', 'Caroline_B2011', 0, '50-64'),
('C0049', 'PHLee7ca', 1, '50-64'),
('C0050', 'Zooteny', 0, '35-49'),
('C0051', '2BeAlive', 0, '50-64'),
('C0052', 'theriverdaleway', 0, '25-34'),
('C0053', 'Sandra Y', 0, '50-64'),
('C0054', '1771', 0, '50-64'),
('C0055', 'surmanator', 0, '35-49'),
('C0056', 'melanieboycs', 0, '25-34'),
('C0057', 'FinnyElTraveler', 1, '25-34'),
('C0058', 'Peter K', 1, '65+'),
('C0059', '29Lorenzo', 0, '50-64'),
('C0060', 'Santababy48238', 0, '35-49'),
('C0061', 'charless923', 1, '35-49'),
('C0062', 'Retired Traveler', 1, '65+'),
('C0063', '197stevee', 1, '25-34'),
('C0064', 'Califanna348', 1, '50-64'),
('C0065', 'Marty M', 1, '65+'),
('C0066', 'Taylor. Ali', 0, '50-64'),
('C0067', 'SinginSuzi', 0, '35-49'),
('C0068', 'Stick55', 1, '25-34'),
('C0069', 'Heather W', 0, '35-49'),
('C0070', 'William T', 1, '35-49'),
('C0071', 'Lisa B', 0, '35-49'),
('C0072', 'Corina M', 0, '50-64'),
('C0073', 'jxx9595', 1, '65+'),
('C0074', 'MissDivaDoll', 0, '35-49'),
('C0075', 'spacemountainmom', 0, '50-64'),
('C0076', 'Just_Me_Bernie', 0, '50-64'),
('C0077', 'westernfb', 1, '50-64'),
('C0078', 'Krishna Bhavithavya Kidambi', 1, '25-34'),
('C0079', 'AnnieMF', 0, '35-49'),
('C0080', 'ipswichpam', 1, '25-34'),
('C0081', 'VPR', 0, '50-64'),
('C0082', 'Russell3939', 1, '35-49'),
('C0083', 'blairkk25', 1, '50-64'),
('C0084', 'David R', 1, '50-64'),
('C0085', 'Sky61', 1, '50-64'),
('C0086', 'elleoa', 0, '18-24'),
('C0087', 'erussell84', 1, '25-34'),
('C0088', 'Gabby914', 1, '25-34'),
('C0089', 'Gearoid9', 1, '35-49'),
('C0090', 'darxhow', 1, '35-49'),
('C0091', 'Eugene S', 1, '50-64'),
('C0092', 'HickoryRidge', 1, '50-64'),
('C0093', 'Lanitac', 0, '35-49'),
('C0094', 'JustinEiseleTravel', 1, '25-34'),
('C0095', 'emped0cles', 1, '35-49'),
('C0096', 'Roya B', 0, '35-49'),
('C0097', 'Marcel H', 1, '35-49'),
('C0098', 'User264339', 1, '50-64'),
('C0099', 'LLQ17', 0, '50-64'),
('C0100', 'Robert J', 1, '65+'),
('C0101', 'craig1086', 1, '25-34');

INSERT INTO [Master_Lee's.Review] VALUES
(4, 'We''ve been there a couple of times and have had 3 for dinner and as many as 9. It''s great to let everyone get whatever they want on their pizza, even GLUTEN FREE and they are all very good and fresh. It''s reasonable, flavorful and thin crust.', '2019-02-13', 'R1003', 'C0001'),
(4, 'I only didn''t like the black stuff the came off the pizza from being slightly burnt. Other than that the pizza was worth the $8 and the quality was exceptional!', '2018-07-19', 'R1003', 'C0002'),
(4, 'This is a decent Pizza place if you like a thin crust pizza as it serves only thin crust pizzas. Cost is same as other pizza places in College Park.', '2018-07-04', 'R1003', 'C0003'),
(5, 'There''s all kinds of pizza joints these days with all sorts of claims to fame but us Marylanders, even those who have move away, always come back to Ledo''s for our cheesy delights. The crust is light and thin. Sauce delicious and I still love my square slices.', '2018-11-04', 'R1002', 'C0004'),
(1, 'This food was so terrible, I couldn''t eat more than a bite. The salad is literally bagged salad you could buy at any grocery store. The eggplant parm had zero flavor, no seasoning what so ever. The food took a long time to arrive and the waiters were inattentive.', '2019-10-30', 'R1002', 'C0005'),
(3, 'I''ve been dying to check a Blaze restaurant out for over a year. Lots of great reviews have come across my feed from fellow yelpers. I will have a lot of positive on this review, but enough negative I cannot get them to a 4', '2018-01-31', 'R1003', 'C0006'),
(5, 'This place was fast and their excellent customer service does not compare with any other pizza place I’ve been too. Very healthy at a reasonable price. You can create your own pizza with unlimited options or choose their options. For veggie lovers, their fresh products makes it better. You also get some tips on how to make a pizza at home. Parking is in front of this place but make sure you take some quarters with you.', '2018-01-20', 'R1003', 'C0007'),
(4, 'A group from high school gathered for a Saturday reunion. The pizza was great. Good friendly service as usual. My only complaint is that you have to pay for parking to enjoy a meal at Ledo''s. Whatever happened to free parking?', '2018-10-14', 'R1002', 'C0008'),
(3, 'I am a HUGE ledo''s fan, usually eat at a different ledo''s, but my family moved closer to this one so I tried it thinking it was the same. Its not. The food was good, but not the usually great Ledo''s I am used to. The pizza was round and not square and super cheesy, which isn''t a bad thing, but just wasn''t right. It was good, would go there again if I had to, but NOT if I want my usual delicious ledo''s I crave when I am out of the country. I have to say I was disappointed that I didn''t have my Ledo''s this time around. The place is older, close to the university which works for students. The parking is metered so be prepared for that. Service was great though, we went at lunch time, wasn''t too busy so that was a start.', '2018-06-13', 'R1002', 'C0009'),
(5, 'This place is mainly known for their pizza and boy is it amazing!!! It''s a staple to Maryland and DC as Imo''s and Talayna''s is to St.Louis, Missouri. I recently had their buffalo wings which for pretty good and I''ve heard their salads are great too. Overall, this is a place you go to get great pizza. The crust is flaky and just has this goodness that''s undescribable until you taste it. Every time my family visits from Missouri they beg us to order this pizza. You can''t go wrong.', '2017-05-22', 'R1002', 'C0010'),
(4, 'Stopped in yesterday for a quick slice to go. I ordered a sausage and peperoni slice it was done in no time. For $3.50 its a decent deal for a large slice of pizza.', '2015-08-19', 'R1005', 'C0011'),
(4, 'We were staying at "The Hotel" and this is right next to it, so very convenient for quick bite. We were here on a Friday and they good lunch specials. We all got something different pizza or a hero. The Italian hero was a nice size and came with a cup of soup. Both were tasty. The pizza unfortunately was not good. The kids and my husband were disappointed. Service was attentive.', '2019-01-29', 'R1001', 'C0012'),
(4, 'Location was in our hotel. Quick delivery made easy. Pizza was tasty and fresh. Staff was polite and helpful.', '2019-07-16', 'R1001', 'C0013'),
(4, 'For food while attending a meeting at "The Hotel", this pizza place just outside the door and in the same building is very handy and much less expensive than the MD Grill inside The Hotel. Portions are huge, so consider sharing. A small pizza is more than adequate for two.', '2019-05-22', 'R1001', 'C0014'),
(3, 'The rather new “The Hotel” across Baltimore Avenue from the Univ. of Maryland has (or had) four restaurants. The one associated with The Hotel (OMG = Old Maryland Grill) is an expensive and rather mediocre choice. Another in the same building, but under separate management, closes at 4 pm. A Greek restaurant went out of business a few months ago. So all that remains as an alternative to the main restaurant is Potomac Pizza (part of a small Maryland chain), which is in The Hotel building but accessible only by walking outside. It is a modest, casual place, catering to take-out food. You can also have it delivered to your room in The Hotel. But there are places to sit and order pizza or other Italian dishes. You would never know it from the menu, but it is possible to ask for an alcoholic beverage, like red or white wine or one of a few beers. The food portions are extremely large, but some items are relatively good, like eggplant parm. The linguine was terrible. Pizza was perhaps better than average, the calzone not so much. It is not like being in Italy, but then it is not like paying a fortune for mediocre food in the main OMG restaurant in the convention hotel. (Other restaurants are at least a quarter-mile walk away.)', '2019-05-07', 'R1001', 'C0015'),
(3, 'Service is good, pizza is not great. Sandwiches are decent. The fries were ok. The beer selection is good.', '2019-03-04', 'R1001', 'C0016'),
(4, 'Good pie, good people We made a good decision by stopping by.  The pizza, while a little high at $17.95, was very good. Waaay better than the cookie-cutter variety we''re used to back home. The thin slices feed you sufficiently but not to a state of over-bloadedness. Exactly what should happen. Very good crust.   The folks here are very friendly and easy to talk with. Very helpful staff and owner.   If you''re looking for a genuine New York Style pizza, this is the place.', '2015-05-17', 'R1005', 'C0017'),
(4, 'We stayed nearby in College Park at the Ramada Inn, and wanted some dinner around 9 at night. We tried out Slices, and were glad we did! On a Sunday night, it was not busy at all and we got our pizza right away. They have VERY large slices of pizza, one should fill you up. They have the normal types of pizza, but then some crazy ones like Mac n Cheese pizza (it''s delicious!). For 2 slices, 2 sodas, and a garlic knot (very tasty) our total was about $11, not too bad. It''s a college town, and fairly affordable pizza. We liked it :)', '2014-10-01', 'R1005', 'C0018'),
(3, 'After 3 visits, it''s consistent: really great slices of pepperoni, if a little expensive, but not very good "fancy" pizzas. On the most recent visit, the pepperoni slice was crispy-crusted, fresh-tasting, with a good balance of cheese and sauce, dripping with oil. Yum. But by comparison, a meat-lovers slice was leaden and salty and not warmed all the way through, and was still sitting heavy in my stomach hours later. Considering those 2 slices were $7.40, the budget-minded should probably get a whole pizza somewhere else for only a few bucks more (and have enough for leftovers, or to share). If you''re hankering for one slice, go here and get the pepperoni, but not the place for something fancier, or for a whole meal.', '2014-04-22', 'R1005', 'C0019'),
(4, 'I''ve only been there twice but both times the pizza was very good. It''s an interesting concept with being a drive thru pizza by the slice place but I liked it enough to go back. I''m just not sure about eating pizza in my car since I need a bib to protect my shirt and seat belt strap. Never the less, if you are hungry for a slice and a soft drink give them a try.', '2018-02-13', 'R1005', 'C0020'),
(4, 'Came in for a family lunch and we ordered fried mozzarella and Antipasto Italiano…. The salad was terrific! Our pizzas 🍕 came out later and we had a combo pizza and Margarita pizza. Both were below average tasting but the crust was perfectly cooked.', '2021-06-27', 'R1004', 'C0021'),
(3, 'From the amount of pizza boxes piled behind the counter, this place moves a lot of pizza. My son tried a plain cheese pizza which is exactly what he got. We would have to try other pizzas in order to comare to others that we know. For the price of a 14 inch pizza, we have had better. I had the lunch special Pollo Milano ($10) which I thought was very good for the price. A crusted chicken breast over spaghettti noodles with spinach and roasted red peppers. The menu was quite extensive and the server forewarned us that the stromboli takes a good 20-25 minutes to bake so if we were in a hurry that may not be a good idea. The sicilian pizza takes even longer. The interior was not inviting to me. You get funneled down a long channel and then swing to the right or left to the seating areas. I''d go back again for the lunch specials. I hope this was helpful!', '2018-04-01', 'R1004', 'C0022'),
(3, 'Came here with my two boys. The staff was friendly and attentive but the food wasn’t great. I got a Caesar salad which had some wilted lettuce and wasn’t very crispy. My son got the personal pizza which the cheese kept sliding off so he got frustrated and stopped eating. I don’t know that i would come back unless someone could recommend a specific dish that would be worth revisiting.', '2018-07-22', 'R1004', 'C0023'),
(5, 'Had pizza and great Italian food here while staying at Cherry Hill Park. Excellent food, friendly service and fast delivery.', '2020-07-06', 'R1004', 'C0024'),
(5, 'Had a great meal here! The bread was warm and the dipping oil was fantastic! I had a pasta with marinara sauce and mushrooms. It was fantastic. My boyfriend had a meatball sub and he enjoyed it very much!! Our meal was $22 including a soda. Well priced and excellent food. Will return next time I am in the area!', '2018-05-30', 'R1004', 'C0025'),
(4, 'If you are a halal lover or just prefer not to eat pork, Pizza Roma is phenomenal. However, if you just want a great pizza or sub, there are better places. Again, this place is geared toward a niche clientele. They serve that clientele well.', '2017-02-25', 'R1006', 'C0026'),
(5, 'It is a great restaurant for halal food, don''t worry about look but about food. I normally buy dinner from this place almost every week.', '2013-10-18', 'R1006', 'C0027'),
(5, 'The only place I''ll get pizza in College Park. I come from an Italian family that owned a pizzeria in New York. We''re tough critics. Pizza Roma is unequivocally the best around. And the prices are fantastic, even better for dine-in or take-out.', '2017-02-02', 'R1006', 'C0028'),
(3, 'Pizza Roma offers halal Mulsim-friendly meat and the owners and workers are quite nice. However, they are super slow and the pizza is just average, the pasta dishes are overpriced and also nothing special. They have their loyal customers, including the local, nearby Muslim school', '2015-12-25', 'R1006', 'C0029'),
(3, 'Pizza Roma is an unusual place: it appears to be an ordinary, bare-bones pizza joint...the kind of place with soft drink coolers, 1950''s linoleum tile floor, bathrooms way in the back behind the counter, and the ordinary pizza, pasta and sandwich options.', '2018-07-07', 'R1006', 'C0030'),
(3, 'After reading reviews of various pizza joints, we settled on Pizza Kingdom. I noted a recent poor review but ignored if for lack of merit. I''m glad I did, because Pizza Kingdom makes some really good pizza.  We ordered the Kingdom Steak and were delighted with the massive amount of steak on the pie. Another reviewer had stated Pizza Kingdom is ''heavy on ingredients,'' and he wasn''t kidding! The sauce was fantastic, great flavor and consistency. The crust was tasty, not too thick, and well baked.  I was *somewhat* disappointed because I had asked for plates, napkins, and forks to be delivered with the pizza. The person who took my phone order assured me it wasn''t a problem. The driver indicated that he had not been given these items, nor had he been instructed to bring any. Pizza Kingdom adds a $5 delivery charge, and if I''m going to pay extra for delivery, I expect to get what I asked for.  I would''ve given Pizza Kingdom a ''Very Good" rating, but this failure at 2 in the afternoon is unacceptable.', '2016-07-04', 'R1007', 'C0031'),
(4, 'Its a decent pizza pie but the parking is a nightmare as there are limited spots and its a hopping little strip mall. There are cute other eateries there and its next door to the original ... Marathon Deli... the best gyros in CP!', '2016-01-28', 'R1007', 'C0032'),
(3, 'I''ve had their food a few times when I was misfortunate enough to temporarily forget why I don''t usually order anything by pizza by places with "pizza" in the restaurant name. Halfway through you just end up wondering why you''d be compelled to put this stuff in you. The fries are crispy though, which is a plus. You know. If you''re just looking for some crap to fill you up without having to get off your backside and make it yourself, then there you are.', '2015-02-21', 'R1007', 'C0033'),
(5, 'I was at the university with four kids age 6-18. We had been at the zoo all day and we were hungry for pizza. We decided to stop in after driving by. The manager was wonderful. She helped me choose the most economical way to feed 5 people with different tastes. It was so cheesy. All the kids loved it.', '2016-07-25', 'R1007', 'C0034'),
(5, 'They have a huge pizza for only $5 and it''s great after a night out with friends. Pizza is a staple in a college town so I''m glad this place opened up', '2015-03-25', 'R1007', 'C0035'),
(4, 'Our waitress Melissa was friendly and attentive. Menu is a little limited but we found good items. My son had the filet and I had the french dip sandwich. The fries were a bit greasy and not all crisp. Sandwich was good. The fiesta corn was delicious. This place is good for a nice casual meal.', '2019-11-02', 'R1008', 'C0036'),
(2, 'We just had a family Sunday brunch yesterday and need to share some feedback with fellow travelers. As always I try to start with positives. Great location with a beautiful design. We enjoyed the spacious seating and quiet environment for conversation. My guess (hope!) regular lunch and meals better. The brunch concept they offer does not work in our opinion. Even our eat-basically-everything 18-year old food vacuum agreed. To be blunt the food was the same or worse as the "free" included breakfast at a discount national hotel chain. You know the make-your-own waffles and toasted bagels in lobby deal with cold, tasteless scrambled eggs probably from a mix? This restaurant has an interesting idea that doesn''t really work. You are allowed to order two items at a time. Each round came back completely wrong, slow and cold. The fruit salad and honey biscuits were fine. I will try a lunch or dinner but the bruch should be avoided. The service was clumsy and forgetful. Maybe they will work our some wrinkles in a still new restaurant and up their game. Too bad for a choice spot! Time will tell.', '2019-10-21', 'R1008', 'C0037'),
(4, 'I have been at the College Park Grill for dinner. They served me even if it was padt 9 p.m. I had the fillet and a baked potato. They were both excellent. It''s not a cheap place, but it''s value for money. If you ate looking for good meat, that''s the place.', '2019-04-29', 'R1008', 'C0038'),
(5, 'I ordered the grilled salmon; it came with jasmine rice, also sautéed spinach & mushrooms. I asked to have the rice substituted for mashed potatoes and that the salmon be blackened. They easily accomodated both requests. The waitress came to my table quickly, was very pleasant, and checked on me often. The salmon was tender and spiced just right with the blackening seasoning; the vegetables were perfect nice and hot, didn’t need salt, pepper, butter ... nothing additional! I sat near the bar. There plenty of seats at the bar and there are about 8 tables for two that surround the bar. There is also a larger dining area on the other side of the bar. You can see and hear the live jazz from either side of the restaurant. There is free parking (on the weekends) behind the building, at least 3 tiers. You can access The College Park Grill by going through the lobby of The Cambia Hotel. The parking and the restaurant are wheel chair accessible. The parking lot is well lit however, the lights get even brighter when you walk near them. This was a wonderful experience for me; I think I’ve found a new favorite neighborhood joint.', '2019-03-26', 'R1008', 'C0039'),
(5, 'It has a wonderful ambiance with kind wait staff! The food was absolutely amazing, no order is the wrong choice!! The potatoes were amazing as was the artichoke dip!', '2019-03-07', 'R1008', 'C0040'),
(2, 'The wait staff was inexperienced. More importantly for breakfast when restaurant was not busy our meal took long to arrive. We could see part of it under heat lamps for 15 minutes. We asked for it to be delivered even if the rest wasn’t ready so that it wouldn’t be cold. It was cold anyway. The rest of the food came our with some orders incorrect. We did not share bc we had waited so long and needed to be on our way.', '2018-11-18', 'R1008', 'C0041'),
(1, 'They delivered to my apartment complex but refused to come inside the building. Apparently, there were too many black people standing outside the complex for the delivery guy''s comfort. The delivery guy said he was concerned for his safety and he did not want to leave his car unattended. It was 5:00pm in Late June and nobody was doing anything threatening or offensive', '2016-06-28', 'R1009', 'C0042'),
(4, 'Just good old ma and pop pizza shop food. The place looks like it has not changed in 80 years. Great food, reasonable pricing', '2018-01-12', 'R1009', 'C0043'),
(1, 'Ive been eating here 20 plus years and the new owners 250 BBQ are ruining it. Ill be ordering from elsewhere from now on!', '2020-07-13', 'R1009', 'C0044'),
(5, 'I’ve enjoyed this hole-in-the-walk pizza place many times over the last ten years. I used to live nearby...I don’t now but am sure to stop in at Dumm’s when I have a pizza craving.', '2018-01-14', 'R1009', 'C0045'),
(5, 'Dumm''s does not have a great atmosphere, and it''s certainly not a special occasion place. But it has fantastic pizza and a really friendly, neighborhood vibe. It''s locally owned, and the owners expanded to another place around the corner that also sells craft beer and good wine. I can''t say enough good things about it!', '2015-04-22', 'R1009', 'C0034'),
(4, 'Dropped by with a huge group of family members and got three pizzas along with several other small orders very quickly. The pizza was piping hot and tasty too. The seating was a bit dodgy at first, but we all managed to sit together. The servers were friendly and happy to help in any way they could. One note for folks, the pizzas are huge and very filling. We left with about an entire pizza of leftovers (which were also very tasty). There is also a full bar, but I did not get anything from it. Some family members did and said that the service was pretty bad. Just an FYI.', '2017-09-07', 'R1010', 'C0047'),
(2, 'the chicken parm and pasta for $13.99 tasted like something from a tv dinner so I wasn''t happy that this dinner that I split with my son with a soda and beer cost over $20 before tip (there''s no waiter service - you order at the counter and the food is brought to you but I still left a couple of bucks for the bus boy.)', '2016-07-11', 'R1010', 'C0048'),
(3, 'Had lunch with a colleague at the Three Brothers this week on his recommendation. It''s in the Beltway Plaza. Plaza''s a bit run down but the food at 3B is pretty good. I had the Lunch Baked Ziti special ($7.99), comes with a side of garlic toast. Very good value. The portion was pretty large and I couldn''t eat it all. My colleague enjoyed his usual Chicken Philly Cheesesteak....took a while to get it though. Café style, no table service. Good for a quick, casual lunch', '2015-10-31', 'R1010', 'C0049'),
(3, 'This is a restaurant in Beltway plaza and is not long on ambience so not really a dine-in with your date kind of place (although great for pre- or post- movie). That said, the food is good American-Italian: cheesy, tomato-y, pasta-y goodness. Price is quite low for large portions - a great deal. Definitely recommend the veggie calzone and the Bianca pizza (15 bucks for a large that would feed three easily and yummy, too!). Suggest you call them the next time you want take out and see what you think!', '2015-07-30', 'R1010', 'C0050'),
(3, 'We chose this restaurant based on Trip Advisor reviews but had not seen that it is a little like a food court venue. You order dinner and pay at a walk up counter and the staff brings your food to you when it is ready. It is a large place, well lit. We had excellent salads, pasta, calzone and eggplant. Also a glass of wine. The staff was friendly even though we arrived within 40 minutes of closing (which is 9 pm). We had entered through a bar (from an exterior door) and that may be available after 9 pm but the kitchen closed while we were there.Portions are very large, especially for the price. Good food but not an intimate or relaxing venue.', '2015-07-09', 'R1010', 'C0051'),
(2, 'When i went in this place i felt like bugs would be in my food. I took the word of a friend and ordered anyway. Food was not good... Never again', '2014-12-30', 'R1011', 'C0052'),
(4, 'I have been getting pizza at this restaurant since I was a kid and I''m now in my 50''s. My teenage son loves the inside of this place and all of the hats on the ceiling and memorabilia on the wall. The staff is always pleasant and they talk to you while you wait for your order. We get the pizza which is thin crust and we love all the toppings that are offered. My son likes the meatball sub which has been a favorite for many years.', '2016-07-30', 'R1011', 'C0053'),
(5, 'Accidentally found this glow in the wall. What a find. Pizza was great. Tacos great and BBQ great with Jack Daniel Sauce. The owner is a treat also. The walls are full of memories. Not a lot of sit down space but it is worth waiting on a table. The menu appeared massive.', '2016-11-08', 'R1011', 'C0054'),
(4, 'Pizza Oven is a small local restaurant with good food and friendly service. Large menu! They offer BBQ items that are made right in front of the establishment. There is a daily lunch special for $5 which includes a small pizza and small drink. Only draw back is that you must pay using cash, cards and checks are not accepted.', '2014-09-14', 'R1011', 'C0055'),
(3, 'We have lived near and regularly ordered from this restaurant for more than 15 years. It is locally owned and delicious. Warning, they don''t take credit cards, so make sure you have cash.', '2017-07-14', 'R1011', 'C0056'),
(4, 'This is my new favorite spot in Hyattsville, Maryland-- what is quickly becoming a typo of "Brooklyn" area of the DMV. It is bustling with new shops, galleries, restaurants and even a Whole Foods. But what I really enjoy are these locally owned businesses that do well--and this place has a phenomenal atmosphere, great pizza, & a locally-stacked beer list ( if you are into that). Always packed and always a great time and great staff.', '2018-08-02', 'R1012', 'C0057'),
(5, 'Five of us had dinner here on 5/10/18. We split three pizzas and thought they were all very good to excellent. The margarita pizza with added goat cheese was excellent as was the paradiso pizza with ricotta cheese and meatballs. The paradiso with sausage, and meatballs was very good. We ate in doors but there is a nice outside area which was very popular. Parking can be tight. We''d recommend this restaurant and will be back.', '2018-05-14', 'R1012', 'C0058'),
(4, 'This is an area of town where there are multiple places to get pizza. So, it is not hard to find a good pizza with all the competition. That said, Pizza Paradiso deserves your business. The pizzas come in 9 and 12 inches for individual servings. Crisp, thin crust with a good selection of toppings. They have an excellent beer selection with a rotating selection of beers on tap that are always interesting and a can/bottle list of beers as well. Wine of course too. We come here often with friends after going to the movies. Everyone is always happy with their meal. Pizza Paradiso fought a long zoning battle to reuse this former, historically designated, flower shop for the restaurant and adjacent art space. For this reason alone, they deserve our support. Having good food and beverage makes it all the easier to support them.', '2018-03-07', 'R1012', 'C0059'),
(4, 'So hubby and i wanted pizza. I didn''t want pizza from Blaze in CP cause the verbs looked like they had been sitting on a hot counter all day. We opted for a wheat base and three meats. Our wasd really good although I would have liked a slightly thicker crust. It''s local to Hyattsville, Mt. Rainer, Brentwood and not far from the DC line.', '2018-02-27', 'R1012', 'C0060'),
(4, 'Grew up in this area. Was old Marche''s Florist. Glad to see it put back to good use. Part of the Hyattsville revitalization. Came in on a Friday night with family and friends, wow very nice setting. Seems like a great neighborhood hangout. Clean, a little tight. Staff, very good, friendly, food served promptly .Pizza, excellent, great crust, good selection. Very nice beer and wine selection. Reasonably priced.Just a great overall experience. Will be back again, no doubt!', '2017-12-05', 'R1012', 'C0061'),
(4, 'Roscoe''s does a fine job with individual sized pizzas and daily pasta specials (which are my usual choice). The menu is imaginative and I''ve enjoyed everything I ever had here.For a neighborhood place in Takoma Park, I''d like to see entrees a dollar or two less than they average and wine at less than downtown DC prices per glass. I''m spoiled by the 5 euro half litres of house we recently enjoyed throughout Italy. That''s around 1 euro a glass. Makes $13 a glass a lot harder to swallow.When I go on my own, I sit at the bar and thoroughly enjoy it.', '2020-02-16', 'R1013', 'C0062'),
(5, 'Went to Roscoe''s on a date with my now wife. The food was delicious and the service was very good and friendly. The location is very convenient and provides easy access to the rest of the area. The atmosphere was wonderful and enabled us to have a great time on the date. I definitely recommend this establishment, and encourage folks to visit. Safe travels!', '2019-05-15', 'R1013', 'C0063'),
(4, 'I had heard that Roscoe''s had the best pizza and after this visit, I can tell you that I agree that it is the best! We ordered Antica and Prosciutto Arugula pizzas and really liked that both had a generous amount of toppings. Also, our waiter, David, was on top of everything and even brought a very chilled glass for our beer. The entrance is wheelchair accessible but the restaurant is a bit tight between tables. However, the staff did accommodate our change from one table to another because the wheels were jutting out into the walkway. The bar is not wheelchair accessible as it has the typical high top. The accessible restrooms are located towards the middle of the restaurant via a hallway, where you will find the entrance to Dolci Gelati (All natural, Italian Gelato and Sorbet). The accessible parking lot (flat but no handicap marked spots) is at 7000 Carroll Avenue at a cost of $5.00; but if you are lucky, you might secure a spot on the street as well. From that parking lot, there is a cut through to Carroll Ave where Mark''s Kitchen is located. You then proceed east along Carroll to Roscoe''s Pizzeria. The sidewalk is mostly brick, so lookout for dips and loose bricks.', '2018-11-07', 'R1013', 'C0064'),
(4, '2 adults and 2 toddlers ate outside on a late Sunday afternoon and they were very quick to bring a small kids'' pizza out for the toddlers who do not understand about waiting for their dinner once they get strapped into their highchairs. I had a Negroni (don''t see them to often!) cocktail and a capresi salad - excellent! The very helpful waitress then wrapped up the meal with 2 small vanilla gelatos for the kids. Just right, no fuss, no bother. A+ experience all around.', '2018-07-25', 'R1013', 'C0065'),
(3, 'Inside and outside seating. Very pleasant restaurant/cafe with Italian menu. Pizza was good, salad pretty good too. Dressing a little over what I would like but I did forget to ask for it on the side. Waiters attentive and accommodating. Child friendly and there is no feeling of being rushed. Would recommend for family lunch and friend catch up.', '2017-09-01', 'R1013', 'C0066'),
(2, 'Got put on hold twice and hung up on should’ve noticed that things were not going well. Ordered food anyway took over an hour to get it when they said it would be a half an hour. Food arrived cold and very tasteless won’t order here again.', '2019-09-15', 'R1015', 'C0067'),
(2, 'I ordered through the über eats app and I selected what I wanted on my burger and the restaurant didn''t follow those instructions I''m allergic to onions and I did not select onions however when food arrived it was covered in onions. Secondly the songs looked as if they had been cooked hours prior to me ordering. Horrible experience don''t even think I''ll give them another try it was such a bad experience', '2016-08-16', 'R1015', 'C0068'),
(1, 'One of two (possibly both) things are true of this location :', '2015-07-24', 'R1015', 'C0069'),
(1, 'I would have rather eaten cardboard with ketchup and cheese than eat this pizza again. It was cold and had no taste. The fact that they serve this as pizza is an absolute joke.', '2013-04-09', 'R1015', 'C0070'),
(5, 'When supper is running late, Manny and Olga''s is on speed dial. Next best thing to Ciro''s Pizza in Stuarts Draft, VA.', '2012-03-30', 'R1015', 'C0071'),
(3, 'Best way to choose how your pizza is made. Great ingredients, tasty and a good size for the price. Service was mediocre as they act like they don''t speak English.', '2021-02-05', 'R1014', 'C0072'),
(1, 'I waited for over half an hour for my pizza and then got extremely sick from it. Go someplace else for pizza. It really wasn''t very good, and if you''re from Philly or NYC, avoid this pizza chain like the plague.', '2016-09-30', 'R1014', 'C0073'),
(4, 'I do not eat meat so whenever I go to & pizza I get the Mushroom Moonstruck pizza. It is delicious. The ingredients tasted fresh and the customer service was good. It was crowded but everything moved quickly. I recommend this location.', '2019-08-06', 'R1014', 'C0074'),
(5, 'Loved the crust and pizza was tasty...they don’t have some typical toppings like plain red onions..they were pickled. Different flavor fountain sodas, no Diet Coke here.', '2019-07-14', 'R1014', 'C0075'),
(4, 'I love creating my own pizza with the delectable toppings that they offer. I''m also fond of the selection of beverages.', '2019-06-26', 'R1014', 'C0076'),
(4, 'I agree with another reviewer that this place is like the "Chipotle for Indian food." You go to a counter, choose your base, meat, etc. We ordered a chicken curry and lamb biryani, and both were great (as was the accompanying naan and raita). I wasn''t expecting that for some reason. The flavors were satisfyingly complex and quantities were decent. It''s not cheap, however, at least not like "fast food." I would definitely order here again, if I lived closer.', '2018-09-18', 'R1017', 'C0077'),
(5, 'This place does a twist on Indian food. The taste was authentic in a modern way. The samosa chat was delicious, you can add some chutneys to it to make it according to your taste and the samosa''s were crispy and hot. The kabob platter was good with hot and tender chicken and it fills up your stomach and it comes with a half piece of bread. Finally the pizza was good but you have to know what items go together with the sauces.', '2019-09-27', 'R1017', 'C0078'),
(5, 'This a nice change of pace with fresh Naan, variety of proteins, veggies and combo dishes from kabobs, rice and salads... it''s an assembly line process where you tell the counter servers what to put into your dish. Delicious every time!', '2017-03-08', 'R1017', 'C0079'),
(5, 'Great place to eat in or take out. The food is always fresh and well made. The service is very friendly.', '2017-10-02', 'R1017', 'C0080'),
(3, 'Nice location, quick service, naan was extra big and thick, paneer items were not up to the mark, rice under cooked, don''t think will again go there', '2018-05-18', 'R1017', 'C0081'),
(2, 'The waitress we had was very unfriendly. Upon saying hello, I was greeted with a grunt. Multiple occasions I tried to be friendly and was just ignored. The pizza tasted like something you would get at a ballpark. Why this is the number one rated pizza place in DC as advertised on the front door is beyond me. Based off the staff and average pizza we would not come back.', '2019-10-14', 'R1016', 'C0082'),
(5, 'I ate lunch at Pi Pizzeria in August 2021. I arrived at 12 noon when it was still not very busy. They made me put my name, email and phone number on a sign-in sheet for contact tracing purposes and everyone was wearing masks except while eating. I ordered a deep dish pizza with tomato sauce, mozzarella, spinach, mushrooms and parmesan cheese. It was absolutely delicious and very competitive with Chicago. The service was excellent. I can''t wait to go there again.', '2021-08-20', 'R1016', 'C0083'),
(5, 'I realize deep-dish pizza isn''t for everyone, but the deep-dish pizza at this restaurant is fantastic, with a delicate cornmeal-infused crust that has the texture of shortbread, and with sauce and toppings that are very tasty. If you refuse to try the deep-dish pizza, then try the thin-crust pizza, which my son tells me is very fine as well.', '2020-03-05', 'R1016', 'C0084'),
(3, 'Nice location. Some construction going on and parking is a little tougher to find.   Nice restaurant. Baseball playoffs going on that night so lots noise but not too much.   Food ordered and delivered in reasonable time. Deep dish pizza was not what I expected but nonetheless good. Not outstanding. Crust was not what I am used too. Vegetarian.  Second was thin crust and again not what was expected as a thin crust pizza.   Waitress was just attentive enough but long to get a bill.', '2019-11-22', 'R1016', 'C0085'),
(4, 'Good pizza and we got to take two halves of two different types of pizza (and depths of dish). Good taste and an original pizza experience. Good service, although the layout of the part of the restaurant we were in was a little tight.', '2019-12-02', 'R1016', 'C0086'),
(2, 'I ordered take out from Menomale Pizza for the first time yesterday with high hopes - the restaurant''s pizza was highly recommended by friends. Unfortunately, the expectations they set up on the phone - telling me the order would be ready in 20 minutes - ultimately lead to a very unsatisfactory experience. I arrived 20 minutes after calling to find the place packed. I checked if my order was ready and they said it would be in a few minutes, but I waited another 20 minutes before going back and asking what the delay was. It''s a good thing I asked because they hadn''t even fired my order. I was very unhappy with the service at Menomale. If they had told me 40 minutes on the phone, I would not have minded. But by setting up expectations that it would only take 20 minutes was really a disappointment. At least when I got home the pizza was good, though it''s not my favourite in DC. I will think twice before going back to Menomale.', '2019-04-08', 'R1018', 'C0087'),
(5, 'I''ll admit, I had never heard of Menomale prior to my first visit. That said, I can now say I will be a repeat customer! Menomale makes some of the BEST pizza I have found in Washington, DC. Moreover, Menomale offers EXCELLENT antipasti dishes and a solid draft beer list.', '2018-05-14', 'R1018', 'C0088'),
(3, 'Menomale is an OK pizza joint. It''s small - very small - and offers the Neapolitan style of pizza that isn''t as crispy as other types. I''ve been there a few times over the year and have yet to understand Menomale''s popularity. Staff are pleasant enough but not especially friendly or efficient. The pizza is edible, but by no means worth a journey across town. And the very cramped dining room isn''t exactly endearing. I can see why locals go here - why anyone else does is beyond me.', '2017-07-15', 'R1018', 'C0089'),
(4, 'I had read about the Neapolitan pizza and how the owner shipped the oven from Italy, so I had to stop by when we were in the area. It''s not going to beat my favorite Neapolitan place in NYC (Don Antonio) but it puts 2 Amys to shame. The dough had just the right amount of chew and the crust was not burnt like I''ve experienced at 2 Amys. We had a hummus type appetizer that was great and my wife loved the cannolis (liked them better than thr ones at Terminis in Philly). We will definitely make a return trip.', '2017-07-15', 'R1018', 'C0090'),
(5, 'I ordered the Diavola Pizza. It was great. Perfect size for one but I shared. It is a little spicy, but not bad. We had a group of six (4) and ordered four (4) pizzas. It didn''t take long for the pizzas to arrive. Our group included a vegan. Menomale''s menu included vegan friendly items. The pizzas were great. The Diavola was spicy but not hot. I liked it a lot. Menomale Pizza is a small restaurant. There is a parking lot just around the corner. Not sure the availability on a weekday. We went on a Sunday. The restrooms are very clean. We started outside. It was a little warm and windy so we moved inside with no problem. I also had the Chocolate Truffle. Very good.', '2015-08-31', 'R1018', 'C0091'),
(3, 'Sometimes, you don''t want eclectic cuisine. Roosevelt Center has an Art Déco vibe with 500 seat one-screen movie theatre, the best bakery anywhere (Chef Lou''s), a grocery store that is TRULY a co-op that is a throwback to the 70s yet with eclectic vittles, TWO performance spaces, decent restaurants, and even a takeout pizza parlor. Sometimes, you just want a good burger, fries, and a drink. That''s Generous Joe''s. Nothing outstanding, but homey, food courtish, and good enough. Y''know? Sometimes, that''s all you want and they give you what you expect. Nothing more, nothing less..', '2018-07-13', 'R1019', 'C0092'),
(5, 'I love this place the food is always fresh and tasty. The side salad is a deal for a low price and is enough to eat. The price and portions are just right.', '2016-04-11', 'R1019', 'C0093'),
(4, 'Generous Joe''s was one of the first Greenbelt places that I tried when coming to practice in Maryland at the end of 2014. It is a great place to get takeout from. I think most of the subs are good. But, I think a few are so good that it is hard to ever get anything else. The eggplant parm is almost good enough to have you not pining for a New York deli if you are in withdraws. It is always fresh and perfectly seasoned. They also make a pretty good steak n'' cheese sub. If you get either, you have to add some fries. Make sure to ask for the fries "crispy".', '2015-11-23', 'R1019', 'C0094'),
(3, 'Went here with some former Greenbelt locals. While the food was good, the wait was very - very long and the place was rather dirty. The trash was overflowing, the bathroom was pretty gross, and the tables / floors were a mess. Note that if I was rating this solely for the food and service, it would easily be 4-5 stars. Would give this place another shot next time, but would probably take the food to go.', '2015-09-06', 'R1019', 'C0095'),
(3, 'We used to be able to walk here from our old house. Not the most fabulous food, or the most clean place, but it''s food, and it''s not too expensive, and it has a small town quirk. Perfect for a quick cheap lunch during an outdoor festival.', '2015-04-21', 'R1019', 'C0096'),
(4, 'You order your Italian menu at the counter - cooks prepare your meal in a few minutes in front of you. Fresh ingredients. Fresh and modern interior. And they have a full bar. Modest prices. Good value for your money. Not for your romantic dinner, but ideal with friends, family or just yourself.', '2020-02-02', 'R1020', 'C0097'),
(5, 'Dined Sunday, 11/10 about 3PM. You get a credit card type card to track your selections & pay when you leave. No waiting as there are many stations to choose—pasta, pizza, salad, etc. Upon ordering, your dish is prepared in front of you allowing for substitutions or alterations of ingredients. We had shrimp & spinach pasta with a creamy pesto sauce. My wife chose a marinara sauce instead of creamy pesto. We split the Greek salad—traditional preparation & loaded with creamy Feta cheese. Fresh herbs are on the tables you can harvest and add to your dish as desired. Very enjoyable meal at moderate prices. Highly recommend!', '2019-11-12', 'R1020', 'C0098'),
(5, 'Fresh pasta cooked to order starting with menu items. The cooks are happy to customize orders. Vapiano serves the only reliably consistent Italian dishes no matter which restaurant you visit.', '2019-10-19', 'R1020', 'C0099'),
(5, 'Loved all the stations and the preparation done after you order. They had bruschetta stations, pasta stations, pizza stations, wine/beverage stations. Fascinating to watch', '2019-09-09', 'R1020', 'C0100'),
(5, 'We came in on a Friday Night for dinner. It was its usual busy, but we only had to wait about 15 mins to place our order. The pasta that we ordered was as good as ever, and the bruschetta to start was fantastic. Sat at the bar, because that was basically the only place to sit, due to it being so crowded. Drinks were great as well. For those that have never been, it''s only a few blocks from a metro stop, so its walkable. For the price, it''s one of the best restaurant deals in D.C. also around the corner from bars & clubs.', '2019-04-07', 'R1020', 'C0101');

INSERT INTO [Master_Lee's.DeliveryPlatform] VALUES
('Self_delivery', ''),
('Uber Eats', 'https://www.ubereats.com'),
('Grubhub', 'https://www.grubhub.com'),
('DoorDash', 'https://www.doordash.com/?'),
('Postmates', 'https://postmates.com/'),
('EatStreet', 'https://eatstreet.com'),
('2nd Kitchen', 'https://2ndkitchen.com/'),
('Slice', 'https://slicelife.com/'),
('Caviar', 'https://www.trycaviar.com/'),
('Clover', 'https://www.clover.com/');

INSERT INTO [Master_Lee's.Employ] VALUES
('R1001', 'Self_delivery'),
('R1001', 'Uber Eats'),
('R1001', 'Grubhub'),
('R1001', 'DoorDash'),
('R1001', 'Postmates'),
('R1004', 'Uber Eats'),
('R1004', 'Grubhub'),
('R1004', 'DoorDash'),
('R1004', 'Postmates'),
('R1004', 'Self_delivery'),
('R1006', 'Self_delivery'),
('R1006', 'Uber Eats'),
('R1006', 'Grubhub'),
('R1006', 'DoorDash'),
('R1003', 'Self_delivery'),
('R1003', 'DoorDash'),
('R1003', 'Uber Eats'),
('R1003', 'Postmates'),
('R1005', 'Self_delivery'),
('R1007', 'Uber Eats'),
('R1007', 'Grubhub'),
('R1007', 'DoorDash'),
('R1007', 'Postmates'),
('R1007', 'EatStreet'),
('R1008', 'Grubhub'),
('R1008', 'DoorDash'),
('R1009', 'DoorDash'),
('R1009', 'Uber Eats'),
('R1009', 'Grubhub'),
('R1009', '2nd Kitchen'),
('R1009', 'Self_delivery'),
('R1010', 'DoorDash'),
('R1010', 'Uber Eats'),
('R1010', 'Grubhub'),
('R1010', 'Self_delivery'),
('R1011', 'Self_delivery'),
('R1012', 'DoorDash'),
('R1012', 'Uber Eats'),
('R1012', 'Grubhub'),
('R1012', 'Self_delivery'),
('R1013', 'DoorDash'),
('R1013', 'Uber Eats'),
('R1013', 'Grubhub'),
('R1013', 'Self_delivery'),
('R1014', 'Grubhub'),
('R1014', 'Uber Eats'),
('R1014', 'Postmates'),
('R1015', 'Grubhub'),
('R1015', 'Slice'),
('R1015', 'DoorDash'),
('R1015', 'uber Eats'),
('R1015', 'Self_delivery'),
('R1016', 'DoorDash'),
('R1016', 'uber Eats'),
('R1016', 'Postmates'),
('R1016', 'Grubhub'),
('R1016', 'Caviar'),
('R1017', 'Slice'),
('R1017', 'Grubhub'),
('R1017', 'DoorDash'),
('R1017', 'Postmates'),
('R1017', 'uber Eats'),
('R1017', 'Self_delivery'),
('R1018', 'Self_delivery'),
('R1018', 'DoorDash'),
('R1018', 'Clover'),
('R1019', 'Self_delivery'),
('R1020', 'Self_delivery'),
('R1020', 'Grubhub'),
('R1020', 'DoorDash'),
('R1020', 'Uber Eats');

INSERT INTO [Master_Lee's.Menu] VALUES
('R1001', 'MC001', 1, 1),
('R1002', 'MC002', 2, 0),
('R1003', 'MC003', 1, 1),
('R1004', 'MC004', 2, 1),
('R1005', 'MC005', 1, 0),
('R1006', 'MC006', 1, 0),
('R1007', 'MC007', 1, 1),
('R1008', 'MC008', 3, 1),
('R1009', 'MC009', 1, 1),
('R1010', 'MC010', 1, 1),
('R1011', 'MC011', 2, 0),
('R1012', 'MC012', 2, 1),
('R1013', 'MC013', 2, 1),
('R1014', 'MC014', 1, 0),
('R1015', 'MC015', 1, 0),
('R1016', 'MC016', 3, 1),
('R1017', 'MC017', 1, 1),
('R1018', 'MC018', 3, 1),
('R1019', 'MC019', 2, 1),
('R1020', 'MC020', 3, 1);

INSERT INTO [Master_Lee's.MenuCuisine] VALUES
('R1002', 'MC002', 'Pizza'),
('R1002', 'MC002', 'Sharable appetizer'),
('R1002', 'MC002', 'Salads'),
('R1002', 'MC002', 'Sandwiches'),
('R1002', 'MC002', 'Entrees'),
('R1002', 'MC002', 'Desserts'),
('R1002', 'MC002', 'Subs'),
('R1001', 'MC001', 'Pizza'),
('R1001', 'MC001', 'Calzones'),
('R1001', 'MC001', 'Subs'),
('R1001', 'MC001', 'Pasta'),
('R1001', 'MC001', 'Salads'),
('R1001', 'MC001', 'Desserts'),
('R1004', 'MC004', 'Pizza'),
('R1004', 'MC004', 'Appetizers'),
('R1004', 'MC004', 'Salads'),
('R1004', 'MC004', 'Pastas'),
('R1004', 'MC004', 'Chicken'),
('R1004', 'MC004', 'Seafood'),
('R1004', 'MC004', 'Protein'),
('R1004', 'MC004', 'Subs'),
('R1004', 'MC004', 'Sides'),
('R1006', 'MC006', 'Pizza'),
('R1006', 'MC006', 'calzones'),
('R1006', 'MC006', 'Pasta'),
('R1006', 'MC006', 'Salads'),
('R1006', 'MC006', 'Subs'),
('R1006', 'MC006', 'Desserts'),
('R1003', 'MC003', 'Pizza'),
('R1003', 'MC003', 'Salads'),
('R1003', 'MC003', 'Desserts'),
('R1005', 'MC005', 'Pizza'),
('R1005', 'MC005', 'Soft drinks'),
('R1005', 'MC005', 'Desserts'),
('R1005', 'MC005', 'Appetizers'),
('R1007', 'MC007', 'Appetizers'),
('R1007', 'MC007', 'Salads'),
('R1007', 'MC007', 'Pizza'),
('R1007', 'MC007', 'Stromboli'),
('R1007', 'MC007', 'Subs'),
('R1007', 'MC007', 'Desserts'),
('R1007', 'MC007', 'Pasta'),
('R1009', 'MC009', 'Pizza'),
('R1009', 'MC009', 'wings'),
('R1009', 'MC009', 'fried snacks'),
('R1009', 'MC009', 'gyros'),
('R1009', 'MC009', 'Subs'),
('R1009', 'MC009', 'wraps'),
('R1009', 'MC009', 'Salads'),
('R1009', 'MC009', 'Desserts'),
('R1010', 'MC010', 'Appetizers'),
('R1010', 'MC010', 'Salads'),
('R1010', 'MC010', 'Lite Lane'),
('R1010', 'MC010', 'Pizza'),
('R1010', 'MC010', 'Entrees'),
('R1010', 'MC010', 'Wraps'),
('R1010', 'MC010', 'Subs'),
('R1011', 'MC011', 'Pizza'),
('R1011', 'MC011', 'Sandwiches'),
('R1011', 'MC011', 'Subs'),
('R1011', 'MC011', 'Pasta'),
('R1011', 'MC011', 'Salads'),
('R1011', 'MC011', 'Wings'),
('R1012', 'MC012', 'Salads'),
('R1012', 'MC012', 'Pizza'),
('R1012', 'MC012', 'Entrees'),
('R1012', 'MC012', 'Sandwiches'),
('R1013', 'MC013', 'Appetizers'),
('R1013', 'MC013', 'Salads'),
('R1013', 'MC013', 'Toasts'),
('R1013', 'MC013', 'Pizza'),
('R1013', 'MC013', 'Sandwiches'),
('R1008', 'MC008', 'Sandwiches'),
('R1008', 'MC008', 'Salads'),
('R1008', 'MC008', 'PIzza'),
('R1008', 'MC008', 'Entrees'),
('R1008', 'MC008', 'Starters'),
('R1014', 'MC014', 'Pizza'),
('R1014', 'MC014', 'Cookies'),
('R1014', 'MC014', 'Drinks'),
('R1015', 'MC015', 'Pizza'),
('R1015', 'MC015', 'Salads'),
('R1015', 'MC015', 'Calzones'),
('R1015', 'MC015', 'Subs'),
('R1015', 'MC015', 'Sides'),
('R1015', 'MC015', 'Specialties'),
('R1016', 'MC016', 'Snacks'),
('R1016', 'MC016', 'Salads'),
('R1016', 'MC016', 'Pizza'),
('R1016', 'MC016', 'Desserts'),
('R1017', 'MC017', 'Pizza'),
('R1017', 'MC017', 'Salads'),
('R1017', 'MC017', 'Desserts'),
('R1017', 'MC017', 'caterings'),
('R1017', 'MC017', 'extras'),
('R1018', 'MC018', 'Salads'),
('R1018', 'MC018', 'Appetizers'),
('R1018', 'MC018', 'Frying'),
('R1018', 'MC018', 'Bruschetta'),
('R1018', 'MC018', 'Pizza'),
('R1018', 'MC018', 'Calzone'),
('R1018', 'MC018', 'Panuozzo'),
('R1018', 'MC018', 'Dessert'),
('R1018', 'MC018', 'Drinks'),
('R1019', 'MC019', 'Salads'),
('R1019', 'MC019', 'Wings'),
('R1019', 'MC019', 'Calzone'),
('R1019', 'MC019', 'Pizza'),
('R1019', 'MC019', 'Sides'),
('R1019', 'MC019', 'Subs'),
('R1019', 'MC019', 'Sandwiches'),
('R1019', 'MC019', 'Desserts'),
('R1019', 'MC019', 'Breakfast'),
('R1020', 'MC020', 'Pizza'),
('R1020', 'MC020', 'Salads'),
('R1020', 'MC020', 'Desserts'),
('R1020', 'MC020', 'Panini'),
('R1020', 'MC020', 'Pasta'),
('R1020', 'MC020', 'Risotto'),
('R1020', 'MC020', 'Appetizers'),
('R1020', 'MC020', 'Soups');

SELECT * FROM [Master_Lee's.Restaurant]
SELECT * FROM [Master_Lee's.Customer]
SELECT * FROM [Master_Lee's.Review]
SELECT * FROM [Master_Lee's.DeliveryPlatform]
SELECT * FROM [Master_Lee's.Employ]
SELECT * FROM [Master_Lee's.Menu]
SELECT * FROM [Master_Lee's.MenuCuisine]

SET ANSI_WARNINGS ON;

COMMIT;

